// Code generated by Slice Machine. DO NOT EDIT.

import Anchor from "./Anchor/index.svelte"
import CallToAction from "./CallToAction/index.svelte"
import Image from "./Image/index.svelte"
import PageIntro from "./PageIntro/index.svelte"

export const components = {
	anchor: Anchor,
	call_to_action: CallToAction,
	image: Image,
	page_intro: PageIntro
}
